apiVersion: v2
name: ala-species-lists
description: A Helm chart for Kubernetes
type: application
version: 1.0.0

dependencies:
  - name: elasticsearch
    version: 1.0.0
    repository: file://charts/elasticsearch
    condition: single_node_es

