{{/*{{- if .Values.serviceAccount.create -}}*/}}
{{/*apiVersion: v1*/}}
{{/*kind: ServiceAccount*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "ala-species-lists.serviceAccountName" . }}*/}}
{{/*  labels:*/}}
{{/*    {{- include "ala-species-lists.labels" . | nindent 4 }}*/}}
{{/*  {{- with .Values.serviceAccount.annotations }}*/}}
{{/*  annotations:*/}}
{{/*    {{- toYaml . | nindent 4 }}*/}}
{{/*  {{- end }}*/}}
{{/*automountServiceAccountToken: {{ .Values.serviceAccount.automount }}*/}}
{{/*{{- end }}*/}}
