replicaCount: 1
image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.3"
resources:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
env:
  - name: node.name
    value: "elasticsearch"
  - name: xpack.security.enabled
    value: "false"
  - name: discovery.type
    value: "single-node"
service:
  name: elasticsearch
  host: elasticsearch
  port: 9200
deployment:
  name: elasticsearch
persistence:
  enabled: true
  storageClass: "auto-ebs-sc"
  accessMode: ReadWriteOnce
  size: 5Gi

single_node_es: true